Close-ActiveSessions $env:computername -ID 1
Close-ActiveSessions $env:computername -ID 2
Close-ActiveSessions $env:computername -ID 3
Close-ActiveSessions $env:computername -ID 4
Close-ActiveSessions $env:computername -ID 5
Close-ActiveSessions $env:computername -ID 6
Close-ActiveSessions $env:computername -ID 7
Close-ActiveSessions $env:computername -ID 8
Close-ActiveSessions $env:computername -ID 9
Close-ActiveSessions $env:computername -ID 10
Close-ActiveSessions $env:computername -ID 11
Close-ActiveSessions $env:computername -ID 12
Close-ActiveSessions $env:computername -ID 13
Close-ActiveSessions $env:computername -ID 14
Close-ActiveSessions $env:computername -ID 15
Close-ActiveSessions $env:computername -ID 16
Close-ActiveSessions $env:computername -ID 17
Close-ActiveSessions $env:computername -ID 18
Close-ActiveSessions $env:computername -ID 19
Close-ActiveSessions $env:computername -ID 20